Website = "https://github.com/rashidpathiyil/attendance-tracker"
Details = "A cross-platform attendance tracking application"
Version = "1.0.0"

[Release]
Icon = "icon.png"
Log = "attendance-tracker.log"

[Web]
BackgroundColor = "#ffffff"

[Windows]
CompanyName = "Rashid Pathiyil"
ProductName = "Attendance Tracker"
VersionString = "1.0.0"
IconPath = "icon.png"

[MacOS]
PublisherName = "Rashid Pathiyil"
DisplayName = "Attendance Tracker"
NSDockTileIcon = "icon.png"
NSAppTransportSecurity = true 
